// flow-typed signature: 24310ad9aaf295df83ef1524fe47f89b
// flow-typed version: <<STUB>>/babel-preset-movio_v^1.2.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-movio'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-movio' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-movio/index' {
  declare module.exports: $Exports<'babel-preset-movio'>;
}
declare module 'babel-preset-movio/index.js' {
  declare module.exports: $Exports<'babel-preset-movio'>;
}
