// flow-typed signature: 52fa03f34bd1d9248249a52ade788e0e
// flow-typed version: <<STUB>>/css-module-flow_v^1.0.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'css-module-flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'css-module-flow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'css-module-flow/index' {
  declare module.exports: $Exports<'css-module-flow'>;
}
declare module 'css-module-flow/index.js' {
  declare module.exports: $Exports<'css-module-flow'>;
}
