// flow-typed signature: 043b9e600a4bb86b5723d3e1cf000d53
// flow-typed version: <<STUB>>/react-test-renderer_v^15.4.2/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-test-renderer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

type TestRendererOptions = {
  createNodeMock: (element: React$Element<any>) => any,
}

type ReactTestRendererJSON = {
  type: string,
  props: {[propName: string]: any},
  children: null | Array<string | ReactTestRendererJSON>,
  $$typeof?: Symbol,
};

type Renderer = {
  toJSON: () => ReactTestRendererJSON,
  toTree: (any) => any,
  update: (newElement: React$Element<any>) => void,
  unmount: () => void;
}

declare module 'react-test-renderer' {
  declare module.exports: {
    create: (nextElement: React$Element<any>, options?: TestRendererOptions) => Renderer,
  }
}

